import {
  LayoutDashboard,
  Users,
  BookOpen,
  GraduationCap,
  MessageSquareWarning,
  Wallet,
  Ticket,
  Package,
  Image as ImageIcon,
  Megaphone,
  CalendarDays,
  Settings,
  ScrollText,
  DatabaseBackup,
  ShieldCheck,
  Trash2,
} from "lucide-react";

export const ADMIN_NAV_ITEMS = [
  { href: "/admin/dashboard", label: "نظرة عامة", icon: LayoutDashboard },
  { href: "/admin/users", label: "المستخدمون", icon: Users },
  { href: "/admin/subjects", label: "المواد الدراسية", icon: GraduationCap },
  { href: "/admin/courses", label: "الكورسات والموافقات", icon: BookOpen },
  { href: "/admin/bundles", label: "الباقات", icon: Package },
  { href: "/admin/deletion-requests", label: "طلبات الحذف", icon: Trash2 },
  { href: "/admin/comments", label: "مراجعة التعليقات", icon: MessageSquareWarning },
  { href: "/admin/payments", label: "المدفوعات والتقارير المالية", icon: Wallet },
  { href: "/admin/coupons", label: "الكوبونات", icon: Ticket },
  { href: "/admin/media", label: "مكتبة الوسائط", icon: ImageIcon },
  { href: "/admin/calendar", label: "التقويم الدراسي", icon: CalendarDays },
  { href: "/admin/announcements", label: "الإعلانات", icon: Megaphone },
  { href: "/admin/settings", label: "الإعدادات", icon: Settings },
  { href: "/admin/audit-logs", label: "سجل النشاطات", icon: ScrollText },
  { href: "/admin/backups", label: "النسخ الاحتياطي", icon: DatabaseBackup },
  { href: "/admin/roles", label: "الأدوار والصلاحيات", icon: ShieldCheck },
];
